# Introduction to Seaborn

### What is Seaborn?

Seaborn is a Python data visualization library built on top of Matplotlib.
It provides a high-level interface for creating attractive and informative statistical graphics.

**Seaborn is mainly used in:**

Data Analytics

Data Science

Machine Learning

Exploratory Data Analysis (EDA)

It helps users create beautiful graphs with less code.

### Why Seaborn over Matplotlib?

| Feature                 | Seaborn               | Matplotlib           |
| ----------------------- | --------------------- | -------------------- |
| Ease of use             | Simple and concise    | More coding required |
| Default styles          | Attractive by default | Basic styling        |
| Statistical plots       | Built-in support      | Limited              |
| Integration with Pandas | Excellent             | Moderate             |
| Complex visualizations  | Easy                  | More manual work     |

**Advantages of Seaborn:-**

Better visualization themes

Less code

Built-in statistical functions

Easy handling of DataFrames

Attractive color palettes

### Installing Seaborn

pip install seaborn

!pip install seaborn

### Importing Libraries

In [1]:
import seaborn as sns
import matplotlib.pyplot as plt

##### Explanation

seaborn is imported as sns
matplotlib.pyplot is imported as plt
sns is used for visualization
plt is used to display plots

### Loading Built-in Datasets

Seaborn provides several built-in datasets for practice.

In [2]:
sns.get_dataset_names()

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'dowjones',
 'exercise',
 'flights',
 'fmri',
 'geyser',
 'glue',
 'healthexp',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'seaice',
 'taxis',
 'tips',
 'titanic']

In [3]:
type(sns.get_dataset_names())

list

In [4]:
len(sns.get_dataset_names())

22

In [8]:
iris = sns.load_dataset('iris')
iris

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [9]:
len(iris)

150

In [10]:
diamonds = sns.load_dataset('diamonds')
diamonds

       carat        cut color clarity  depth  table  price     x     y     z
0       0.23      Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1       0.21    Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2       0.23       Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3       0.29    Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4       0.31       Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75
...      ...        ...   ...     ...    ...    ...    ...   ...   ...   ...
53935   0.72      Ideal     D     SI1   60.8   57.0   2757  5.75  5.76  3.50
53936   0.72       Good     D     SI1   63.1   55.0   2757  5.69  5.75  3.61
53937   0.70  Very Good     D     SI1   62.8   60.0   2757  5.66  5.68  3.56
53938   0.86    Premium     H     SI2   61.0   58.0   2757  6.15  6.12  3.74
53939   0.75      Ideal     D     SI2   62.2   55.0   2757  5.83  5.87  3.64

[53940 rows x 10 columns]

### Understanding Dataset

**What is "tips" Dataset?**

The "tips" dataset contains restaurant bill information.

**Columns in Dataset**

| Column     | Meaning                 |
| ---------- | ----------------------- |
| total_bill | Total restaurant bill   |
| tip        | Tip amount              |
| sex        | Gender                  |
| smoker     | Whether customer smokes |
| day        | Day of visit            |
| time       | Lunch or Dinner         |
| size       | Number of people        |

In [11]:
tips = sns.load_dataset('tips')
tips

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

### Checking Dataset Information

##### first 5 rows

In [12]:
tips.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

##### last 5 rows

In [13]:
tips.tail()

     total_bill   tip     sex smoker   day    time  size
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

##### dataset shape

In [14]:
tips.shape

(244, 7)

##### column names

In [15]:
tips.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

##### dataset information

In [16]:
tips.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB

##### statistical summary

In [17]:
tips.describe()

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [30]:
tips = sns.load_dataset('tips')
tips.describe(include = 'all')

        total_bill         tip   sex smoker  day    time        size
count   244.000000  244.000000   244    244  244     244  244.000000
unique         NaN         NaN     2      2    4       2         NaN
top            NaN         NaN  Male     No  Sat  Dinner         NaN
freq           NaN         NaN   157    151   87     176         NaN
mean     19.785943    2.998279   NaN    NaN  NaN     NaN    2.569672
std       8.902412    1.383638   NaN    NaN  NaN     NaN    0.951100
min       3.070000    1.000000   NaN    NaN  NaN     NaN    1.000000
25%      13.347500    2.000000   NaN    NaN  NaN     NaN    2.000000
50%      17.795000    2.900000   NaN    NaN  NaN     NaN    2.000000
75%      24.127500    3.562500   NaN    NaN  NaN     NaN    3.000000
max      50.810000   10.000000   NaN    NaN  NaN     NaN    6.000000

In [33]:
tips.sex.unique()

['Female', 'Male']
Categories (2, object): ['Male', 'Female']

In [34]:
tips.sex.value_counts()

sex
Male      157
Female     87
Name: count, dtype: int64

### Why Built-in Datasets are Useful?

They help in:

Practicing visualization

Learning EDA

Testing plots quickly

Understanding relationships between variables

### Common Built-in Datasets in Seaborn

| Dataset  | Purpose                   |
| -------- | ------------------------- |
| tips     | Restaurant bills          |
| iris     | Flower classification     |
| titanic  | Survival analysis         |
| flights  | Time-series visualization |
| penguins | Classification analysis   |