# Data Selection & Indexing

In [1]:
import pandas as pd

In [48]:
df = pd.read_csv('India_Ecommerce_Unclean_Dataset.csv')

In [4]:
df

,Order_ID,Order_Date,Delivery_Date,Customer_Name,Customer_Email,Customer_Phone,Customer_City,Customer_State,Customer_Pincode,Region,...,Unit_Price_INR,Discount_Percent,Tax_Percent,Gross_Amount_INR,Net_Amount_INR,Payment_Method,Payment_Status,Shipping_Method,Customer_Rating,Return_Status
0,ORD00000001,28/09/2023,07/10/2023,Rohan Agarwal,rohan.agarwal769@yahoo.co.in,9.186701e+11,Chenai,KA,684090.0,NaN,...,119742.81,26.31,5.0,119742.81,92650.40,cash,NaN,Next Day,4.4,N
1,ORD00000002,2023-12-11,2023-12-12,suresh Kumar,suresh.kumar998yahoo.co.in,9.193598e+11,PUNE,Maharashtra,186238.0,East India,...,140712.99,4.39,12.0,984990.93,1054759.81,NaN,Pending,Next Day,4.5,1
2,ORD00000003,2021-10-24,2021-11-04,Sunita Nair,sunita.nair877@yahoo.co.in,9.173318e+11,Indore,Bihar,3803.0,north,...,15846.47,9.26,12.0,63385.88,64418.31,Debit Card,pending,Standard,1.2,NaN
3,ORD00000004,2024-03-31,2024-04-06,Pooja Das,pooja.das184gmail.com,9.171830e+11,Kolkata,Andhra Pradesh,739883.0,SOUTH,...,132045.51,17.80,0.0,1591319.56,1308064.68,Debit Card,Paid,Same Day,4.0,Yes
4,ORD00000005,07-01-2022,07-11-2022,Kavya Sen,kavya.sen379@hotmail.com,9.189122e+11,Ahemadabad,NaN,5454.0,NaN,...,66250.95,45.25,28.0,287771.80,201670.48,upi,NaN,Economy,2.2,No Return
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,ORD00099996,NaN,NaN,Pooja Chopra,pooja.chopra868@gmail.com,9.180279e+11,Mumbai,TN,792197.0,SOUTH,...,32914.31,56.74,18.0,65828.62,33603.40,DEBIT CARD,Paid,standard,1.0,No Return
99996,ORD00036659,2022-05-21,2022-05-27,meena Rao,meena.rao409@hotmail.com,9.168083e+11,PUNE,NaN,614404.0,North,...,57356.55,31.30,5.0,401495.85,289619.03,Cash on Delivery,PAID,Standard,1.4,Yes
99997,ORD00099998,03-Oct-2023,14-Oct-2023,Rahul Patel,rahul.patel827@rediffmail.com,9.195276e+11,NaN,Bihar,250996.0,SOUTH,...,119512.97,22.06,12.0,1075616.73,938935.96,Credit Card,PAID,NaN,1.9,No Return
99998,ORD00099999,2023-10-25,2023-11-05,POOJA Gupta,pooja.gupta101@hotmail.com,9.171351e+11,DELHI,Kerala,990079.0,north,...,34764.23,21.12,18.0,34764.23,32357.99,NaN,Failed,Next Day,4.9,No Return
99999,ORD00100000,01-25-2024,02-06-2024,Kavya Reddy,kavya.reddy225@outlook.com,9.190548e+11,PUNE,Maharashtra,343131.0,Northeast,...,119670.92,57.04,0.0,718025.52,308463.76,DEBIT CARD,PAID,Express,4.2,1

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 25 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Order_ID          99500 non-null   object
 1   Order_Date        98990 non-null   object
 2   Delivery_Date     97031 non-null   object
 3   Customer_Name     99014 non-null   object
 4   Customer_Email    99018 non-null   object
 5   Customer_Phone    98996 non-null   float64
 6   Customer_City     93215 non-null   object
 7   Customer_State    88108 non-null   object
 8   Customer_Pincode  99035 non-null   float64
 9   Region            81744 non-null   object
 10  Category          93659 non-null   object
 11  Sub_Category      98995 non-null   object
 12  Product_Name      97992 non-null   object
 13  Product_SKU       100000 non-null  object
 14  Quantity          100000 non-null  int64
 15  Unit_Price_INR    99500 non-null   object
 16  Discount_Percent  98926 non-null   float64
 17  Tax_Percent       98027 non-null   float64
 18  Gross_Amount_INR  100000 non-null  float64
 19  Net_Amount_INR    97045 non-null   float64
 20  Payment_Method    86780 non-null   object
 21  Payment_Status    82047 non-null   object
 22  Shipping_Method   77579 non-null   object
 23  Customer_Rating   98006 non-null   float64
 24  Return_Status     90628 non-null   object
dtypes: float64(7), int64(1), object(17)
memory usage: 19.1+ MB

### 1.Selection columns

##### single column ----> returns a series(1D)

In [10]:
df['Customer_Phone']

0        9.186701e+11
1        9.193598e+11
2        9.173318e+11
3        9.171830e+11
4        9.189122e+11
             ...
99995    9.180279e+11
99996    9.168083e+11
99997    9.195276e+11
99998    9.171351e+11
99999    9.190548e+11
Name: Customer_Phone, Length: 100000, dtype: float64

In [11]:
df['Return_Status']

0                N
1                1
2              NaN
3              Yes
4        No Return
           ...
99995    No Return
99996          Yes
99997    No Return
99998    No Return
99999            1
Name: Return_Status, Length: 100000, dtype: object

##### multiple columns ----> returns a dataframe (2-D)

In [12]:
df[['Customer_Name','Discount_Percent']]

       Customer_Name  Discount_Percent
0      Rohan Agarwal             26.31
1       suresh Kumar              4.39
2        Sunita Nair              9.26
3          Pooja Das             17.80
4          Kavya Sen             45.25
...              ...               ...
99995   Pooja Chopra             56.74
99996      meena Rao             31.30
99997    Rahul Patel             22.06
99998    POOJA Gupta             21.12
99999    Kavya Reddy             57.04

[100000 rows x 2 columns]

In [13]:
df[['Customer_Name','Discount_Percent','Payment_Method','Payment_Status']]

       Customer_Name  Discount_Percent    Payment_Method Payment_Status
0      Rohan Agarwal             26.31              cash            NaN
1       suresh Kumar              4.39               NaN        Pending
2        Sunita Nair              9.26        Debit Card        pending
3          Pooja Das             17.80        Debit Card           Paid
4          Kavya Sen             45.25               upi            NaN
...              ...               ...               ...            ...
99995   Pooja Chopra             56.74        DEBIT CARD           Paid
99996      meena Rao             31.30  Cash on Delivery           PAID
99997    Rahul Patel             22.06       Credit Card           PAID
99998    POOJA Gupta             21.12               NaN         Failed
99999    Kavya Reddy             57.04        DEBIT CARD           PAID

[100000 rows x 4 columns]

### 2.Row Selection

##### loc[ ] -----> label-based selection , uses index labels(names)

In [14]:
df.loc[0]

Order_ID                             ORD00000001
Order_Date                            28/09/2023
Delivery_Date                         07/10/2023
Customer_Name                      Rohan Agarwal
Customer_Email      rohan.agarwal769@yahoo.co.in
Customer_Phone                    918670137977.0
Customer_City                             Chenai
Customer_State                                KA
Customer_Pincode                        684090.0
Region                                       NaN
Category                                  Beauty
Sub_Category                              Makeup
Product_Name           Beauty - Makeup Model 917
Product_SKU                             SKU49209
Quantity                                       1
Unit_Price_INR                         119742.81
Discount_Percent                           26.31
Tax_Percent                                  5.0
Gross_Amount_INR                       119742.81
Net_Amount_INR                           92650.4
Payment_Method                              cash
Payment_Status                               NaN
Shipping_Method                         Next Day
Customer_Rating                              4.4
Return_Status                                  N
Name: 0, dtype: object

In [15]:
df.loc[5]

Order_ID                          ORD00000006
Order_Date                         2021-09-08
Delivery_Date                      2021-09-18
Customer_Name                    Sanjay Joshi
Customer_Email      sanjay.joshi235@gmail.com
Customer_Phone                 919939351450.0
Customer_City                           DELHI
Customer_State                      Rajasthan
Customer_Pincode                     115208.0
Region                                  SOUTH
Category                               Sports
Sub_Category                             Yoga
Product_Name          Sports - Yoga Model 692
Product_SKU                          SKU21816
Quantity                                    1
Unit_Price_INR                      129473.12
Discount_Percent                        44.04
Tax_Percent                              28.0
Gross_Amount_INR                    129473.12
Net_Amount_INR                       92740.04
Payment_Method                            upi
Payment_Status                           paid
Shipping_Method                      Standard
Customer_Rating                           4.1
Return_Status                             Yes
Name: 5, dtype: object

In [19]:
type(df.loc[5])

pandas.core.series.Series

In [16]:
df.loc[0:5]

,Order_ID,Order_Date,Delivery_Date,Customer_Name,Customer_Email,Customer_Phone,Customer_City,Customer_State,Customer_Pincode,Region,...,Unit_Price_INR,Discount_Percent,Tax_Percent,Gross_Amount_INR,Net_Amount_INR,Payment_Method,Payment_Status,Shipping_Method,Customer_Rating,Return_Status
0,ORD00000001,28/09/2023,07/10/2023,Rohan Agarwal,rohan.agarwal769@yahoo.co.in,9.186701e+11,Chenai,KA,684090.0,NaN,...,119742.81,26.31,5.0,119742.81,92650.40,cash,NaN,Next Day,4.4,N
1,ORD00000002,2023-12-11,2023-12-12,suresh Kumar,suresh.kumar998yahoo.co.in,9.193598e+11,PUNE,Maharashtra,186238.0,East India,...,140712.99,4.39,12.0,984990.93,1054759.81,NaN,Pending,Next Day,4.5,1
2,ORD00000003,2021-10-24,2021-11-04,Sunita Nair,sunita.nair877@yahoo.co.in,9.173318e+11,Indore,Bihar,3803.0,north,...,15846.47,9.26,12.0,63385.88,64418.31,Debit Card,pending,Standard,1.2,NaN
3,ORD00000004,2024-03-31,2024-04-06,Pooja Das,pooja.das184gmail.com,9.171830e+11,Kolkata,Andhra Pradesh,739883.0,SOUTH,...,132045.51,17.80,0.0,1591319.56,1308064.68,Debit Card,Paid,Same Day,4.0,Yes
4,ORD00000005,07-01-2022,07-11-2022,Kavya Sen,kavya.sen379@hotmail.com,9.189122e+11,Ahemadabad,NaN,5454.0,NaN,...,66250.95,45.25,28.0,287771.80,201670.48,upi,NaN,Economy,2.2,No Return
5,ORD00000006,2021-09-08,2021-09-18,Sanjay Joshi,sanjay.joshi235@gmail.com,9.199394e+11,DELHI,Rajasthan,115208.0,SOUTH,...,129473.12,44.04,28.0,129473.12,92740.04,upi,paid,Standard,4.1,Yes

In [20]:
type(df.loc[0:5])

pandas.core.frame.DataFrame

In [17]:
df.loc[4:13]

,Order_ID,Order_Date,Delivery_Date,Customer_Name,Customer_Email,Customer_Phone,Customer_City,Customer_State,Customer_Pincode,Region,...,Unit_Price_INR,Discount_Percent,Tax_Percent,Gross_Amount_INR,Net_Amount_INR,Payment_Method,Payment_Status,Shipping_Method,Customer_Rating,Return_Status
4,ORD00000005,07-01-2022,07-11-2022,Kavya Sen,kavya.sen379@hotmail.com,9.189122e+11,Ahemadabad,NaN,5454.0,NaN,...,66250.95,45.25,28.0,287771.80,201670.48,upi,NaN,Economy,2.2,No Return
5,ORD00000006,2021-09-08,2021-09-18,Sanjay Joshi,sanjay.joshi235@gmail.com,9.199394e+11,DELHI,Rajasthan,115208.0,SOUTH,...,129473.12,44.04,28.0,129473.12,92740.04,upi,paid,Standard,4.1,Yes
6,ORD00000007,2020-01-02,2020-01-04,rajesh Chopra,rajesh.chopra644@outlook.com,9.177525e+11,Mumbai,Haryana,596212.0,East,...,15655.87,56.71,18.0,31311.74,15994.73,COD,FAILED,NaN,1.9,No Return
7,ORD00000008,2022-09-04,2022-09-07,Rajesh Bose,rajesh.bose319@outlook.com,9.183183e+11,Kanpur,Maharashtra,6847.0,Central,...,79629.06,19.59,0.0,557403.42,448208.09,EMI,pending,NaN,1.0,1
8,ORD00000009,2022-10-28,NaN,Deepa Mishra,deepa.mishra375@hotmail.com,9.187953e+11,Indore,DL,920690.0,SOUTH,...,119896.28,47.05,12.0,239792.56,142206.58,COD,pending,EXPRESS,3.8,Y
9,ORD00000010,2024-03-29,2024-04-06,Kavya Gupta,kavya.gupta430@yahoo.co.in,9.186384e+11,Ahmedabad,Gujarat,194758.0,Northeast,...,143389.29,36.43,18.0,1290503.61,968040.31,Debit Card,Failed,EXPRESS,2.2,No
10,ORD00000011,23-Feb-2023,26-Feb-2023,Sneha Rao,sneha.rao820@outlook.com,9.165324e+11,Bangalroe,Tamil Nadu,832151.0,north,...,122287.5,8.46,0.0,244575.00,223883.96,Wallet,NaN,Next Day,4.8,TRUE
11,ORD00000012,2020-02-17,2020-02-29,Vikram Verma,vikram.verma927@rediffmail.com,9.189287e+11,kolkata,MH,715299.0,NaN,...,128489.73,24.99,28.0,899428.11,863566.11,Netbanking,pending,Same Day,3.0,N
12,ORD00000013,2022-06-26,2022-07-09,Meena Iyer,meena.iyer418@gmail.com,9.195131e+11,NaN,maharashtra,5807.0,north,...,118340.98,53.38,0.0,236681.96,110341.13,Net Banking,Complete,Standard,2.3,NaN
13,ORD00000014,03-Apr-2023,07-Apr-2023,Rajesh Reddy,rajesh.reddy741@gmail.com,9.172719e+11,Delhi,NaN,229002.0,Central,...,71393.94,26.57,0.0,642545.46,471821.13,COD,Failed,standard,4.7,NaN

In [18]:
df.loc[2:20:2]

,Order_ID,Order_Date,Delivery_Date,Customer_Name,Customer_Email,Customer_Phone,Customer_City,Customer_State,Customer_Pincode,Region,...,Unit_Price_INR,Discount_Percent,Tax_Percent,Gross_Amount_INR,Net_Amount_INR,Payment_Method,Payment_Status,Shipping_Method,Customer_Rating,Return_Status
2,ORD00000003,2021-10-24,2021-11-04,Sunita Nair,sunita.nair877@yahoo.co.in,9.173318e+11,Indore,Bihar,3803.0,north,...,15846.47,9.26,12.0,63385.88,64418.31,Debit Card,pending,Standard,1.2,NaN
4,ORD00000005,07-01-2022,07-11-2022,Kavya Sen,kavya.sen379@hotmail.com,9.189122e+11,Ahemadabad,NaN,5454.0,NaN,...,66250.95,45.25,28.0,287771.80,201670.48,upi,NaN,Economy,2.2,No Return
6,ORD00000007,2020-01-02,2020-01-04,rajesh Chopra,rajesh.chopra644@outlook.com,9.177525e+11,Mumbai,Haryana,596212.0,East,...,15655.87,56.71,18.0,31311.74,15994.73,COD,FAILED,NaN,1.9,No Return
8,ORD00000009,2022-10-28,NaN,Deepa Mishra,deepa.mishra375@hotmail.com,9.187953e+11,Indore,DL,920690.0,SOUTH,...,119896.28,47.05,12.0,239792.56,142206.58,COD,pending,EXPRESS,3.8,Y
10,ORD00000011,23-Feb-2023,26-Feb-2023,Sneha Rao,sneha.rao820@outlook.com,9.165324e+11,Bangalroe,Tamil Nadu,832151.0,north,...,122287.5,8.46,0.0,244575.00,223883.96,Wallet,NaN,Next Day,4.8,TRUE
12,ORD00000013,2022-06-26,2022-07-09,Meena Iyer,meena.iyer418@gmail.com,9.195131e+11,NaN,maharashtra,5807.0,north,...,118340.98,53.38,0.0,236681.96,110341.13,Net Banking,Complete,Standard,2.3,NaN
14,ORD00000015,2022-03-05,NaN,sanjay Nair,sanjay.nair956@rediffmail.com,9.161828e+11,Bangalore,Punjab,875850.0,NaN,...,110614.49,14.22,5.0,331843.47,298888.09,credit card,PAID,NaN,3.5,Yes
16,ORD00000017,2023-07-19,2023-07-27,Divya Sen,divya.sen544@yahoo.co.in,NaN,Kanpur,KA,587499.0,West,...,142212.88,27.71,28.0,142212.88,131591.28,DEBIT CARD,NaN,NaN,4.9,No Return
18,ORD00000019,2022-12-26,2022-12-31,Pooja Nair,pooja.nair487@rediffmail.com,9.192433e+11,Indore,maharashtra,606040.0,South,...,93013.17,36.37,0.0,465065.85,295921.40,Net Banking,pending,Standard,3.9,No Return
20,ORD00000021,2021-03-20,2021-03-21,Sanjay Nair,sanjay.nair820@hotmail.com,9.178578e+11,NaN,Telangana,902579.0,NaN,...,36608.82,46.28,12.0,146435.28,88104.84,Wallet,Paid,Same Day,1.4,NaN

In [24]:
a = df.loc[[2,10,5],['Order_ID','Customer_Name','Customer_City','Tax_Percent','Shipping_Method']]

In [25]:
a

       Order_ID Customer_Name Customer_City  Tax_Percent Shipping_Method
2   ORD00000003   Sunita Nair        Indore         12.0        Standard
10  ORD00000011     Sneha Rao     Bangalroe          0.0        Next Day
5   ORD00000006  Sanjay Joshi         DELHI         28.0        Standard

In [26]:
type(a)

pandas.core.frame.DataFrame

In [43]:
df.loc[:, ['Customer_Name','Customer_City','Tax_Percent']]

       Customer_Name Customer_City  Tax_Percent
0      Rohan Agarwal        Chenai          5.0
1       suresh Kumar          PUNE         12.0
2        Sunita Nair        Indore         12.0
3          Pooja Das       Kolkata          0.0
4          Kavya Sen    Ahemadabad         28.0
...              ...           ...          ...
99995   Pooja Chopra        Mumbai         18.0
99996      meena Rao          PUNE          5.0
99997    Rahul Patel           NaN         12.0
99998    POOJA Gupta         DELHI         18.0
99999    Kavya Reddy          PUNE          0.0

[100000 rows x 3 columns]

##### iloc [ ] ---> Position-based selection , uses index position (numbers)

In [27]:
df.iloc[0]

Order_ID                             ORD00000001
Order_Date                            28/09/2023
Delivery_Date                         07/10/2023
Customer_Name                      Rohan Agarwal
Customer_Email      rohan.agarwal769@yahoo.co.in
Customer_Phone                    918670137977.0
Customer_City                             Chenai
Customer_State                                KA
Customer_Pincode                        684090.0
Region                                       NaN
Category                                  Beauty
Sub_Category                              Makeup
Product_Name           Beauty - Makeup Model 917
Product_SKU                             SKU49209
Quantity                                       1
Unit_Price_INR                         119742.81
Discount_Percent                           26.31
Tax_Percent                                  5.0
Gross_Amount_INR                       119742.81
Net_Amount_INR                           92650.4
Payment_Method                              cash
Payment_Status                               NaN
Shipping_Method                         Next Day
Customer_Rating                              4.4
Return_Status                                  N
Name: 0, dtype: object

In [29]:
df.iloc[0:5]

,Order_ID,Order_Date,Delivery_Date,Customer_Name,Customer_Email,Customer_Phone,Customer_City,Customer_State,Customer_Pincode,Region,...,Unit_Price_INR,Discount_Percent,Tax_Percent,Gross_Amount_INR,Net_Amount_INR,Payment_Method,Payment_Status,Shipping_Method,Customer_Rating,Return_Status
0,ORD00000001,28/09/2023,07/10/2023,Rohan Agarwal,rohan.agarwal769@yahoo.co.in,9.186701e+11,Chenai,KA,684090.0,NaN,...,119742.81,26.31,5.0,119742.81,92650.40,cash,NaN,Next Day,4.4,N
1,ORD00000002,2023-12-11,2023-12-12,suresh Kumar,suresh.kumar998yahoo.co.in,9.193598e+11,PUNE,Maharashtra,186238.0,East India,...,140712.99,4.39,12.0,984990.93,1054759.81,NaN,Pending,Next Day,4.5,1
2,ORD00000003,2021-10-24,2021-11-04,Sunita Nair,sunita.nair877@yahoo.co.in,9.173318e+11,Indore,Bihar,3803.0,north,...,15846.47,9.26,12.0,63385.88,64418.31,Debit Card,pending,Standard,1.2,NaN
3,ORD00000004,2024-03-31,2024-04-06,Pooja Das,pooja.das184gmail.com,9.171830e+11,Kolkata,Andhra Pradesh,739883.0,SOUTH,...,132045.51,17.80,0.0,1591319.56,1308064.68,Debit Card,Paid,Same Day,4.0,Yes
4,ORD00000005,07-01-2022,07-11-2022,Kavya Sen,kavya.sen379@hotmail.com,9.189122e+11,Ahemadabad,NaN,5454.0,NaN,...,66250.95,45.25,28.0,287771.80,201670.48,upi,NaN,Economy,2.2,No Return

In [32]:
df.iloc[4:11:3]

,Order_ID,Order_Date,Delivery_Date,Customer_Name,Customer_Email,Customer_Phone,Customer_City,Customer_State,Customer_Pincode,Region,...,Unit_Price_INR,Discount_Percent,Tax_Percent,Gross_Amount_INR,Net_Amount_INR,Payment_Method,Payment_Status,Shipping_Method,Customer_Rating,Return_Status
4,ORD00000005,07-01-2022,07-11-2022,Kavya Sen,kavya.sen379@hotmail.com,9.189122e+11,Ahemadabad,NaN,5454.0,NaN,...,66250.95,45.25,28.0,287771.80,201670.48,upi,NaN,Economy,2.2,No Return
7,ORD00000008,2022-09-04,2022-09-07,Rajesh Bose,rajesh.bose319@outlook.com,9.183183e+11,Kanpur,Maharashtra,6847.0,Central,...,79629.06,19.59,0.0,557403.42,448208.09,EMI,pending,NaN,1.0,1
10,ORD00000011,23-Feb-2023,26-Feb-2023,Sneha Rao,sneha.rao820@outlook.com,9.165324e+11,Bangalroe,Tamil Nadu,832151.0,north,...,122287.5,8.46,0.0,244575.00,223883.96,Wallet,NaN,Next Day,4.8,TRUE

In [38]:
df.iloc[[1,4,2],5]

1    9.193598e+11
4    9.189122e+11
2    9.173318e+11
Name: Customer_Phone, dtype: float64

In [37]:
df.loc[[1,4,2],5]

KeyError: 5

In [39]:
df.iloc[[2,5,10], :]

,Order_ID,Order_Date,Delivery_Date,Customer_Name,Customer_Email,Customer_Phone,Customer_City,Customer_State,Customer_Pincode,Region,...,Unit_Price_INR,Discount_Percent,Tax_Percent,Gross_Amount_INR,Net_Amount_INR,Payment_Method,Payment_Status,Shipping_Method,Customer_Rating,Return_Status
2,ORD00000003,2021-10-24,2021-11-04,Sunita Nair,sunita.nair877@yahoo.co.in,9.173318e+11,Indore,Bihar,3803.0,north,...,15846.47,9.26,12.0,63385.88,64418.31,Debit Card,pending,Standard,1.2,NaN
5,ORD00000006,2021-09-08,2021-09-18,Sanjay Joshi,sanjay.joshi235@gmail.com,9.199394e+11,DELHI,Rajasthan,115208.0,SOUTH,...,129473.12,44.04,28.0,129473.12,92740.04,upi,paid,Standard,4.1,Yes
10,ORD00000011,23-Feb-2023,26-Feb-2023,Sneha Rao,sneha.rao820@outlook.com,9.165324e+11,Bangalroe,Tamil Nadu,832151.0,north,...,122287.5,8.46,0.0,244575.00,223883.96,Wallet,NaN,Next Day,4.8,TRUE

In [40]:
df.loc[[2,5,10], :]

,Order_ID,Order_Date,Delivery_Date,Customer_Name,Customer_Email,Customer_Phone,Customer_City,Customer_State,Customer_Pincode,Region,...,Unit_Price_INR,Discount_Percent,Tax_Percent,Gross_Amount_INR,Net_Amount_INR,Payment_Method,Payment_Status,Shipping_Method,Customer_Rating,Return_Status
2,ORD00000003,2021-10-24,2021-11-04,Sunita Nair,sunita.nair877@yahoo.co.in,9.173318e+11,Indore,Bihar,3803.0,north,...,15846.47,9.26,12.0,63385.88,64418.31,Debit Card,pending,Standard,1.2,NaN
5,ORD00000006,2021-09-08,2021-09-18,Sanjay Joshi,sanjay.joshi235@gmail.com,9.199394e+11,DELHI,Rajasthan,115208.0,SOUTH,...,129473.12,44.04,28.0,129473.12,92740.04,upi,paid,Standard,4.1,Yes
10,ORD00000011,23-Feb-2023,26-Feb-2023,Sneha Rao,sneha.rao820@outlook.com,9.165324e+11,Bangalroe,Tamil Nadu,832151.0,north,...,122287.5,8.46,0.0,244575.00,223883.96,Wallet,NaN,Next Day,4.8,TRUE

In [41]:
df.iloc[:, [3, 5, 9]]

       Customer_Name  Customer_Phone      Region
0      Rohan Agarwal    9.186701e+11         NaN
1       suresh Kumar    9.193598e+11  East India
2        Sunita Nair    9.173318e+11       north
3          Pooja Das    9.171830e+11       SOUTH
4          Kavya Sen    9.189122e+11         NaN
...              ...             ...         ...
99995   Pooja Chopra    9.180279e+11       SOUTH
99996      meena Rao    9.168083e+11       North
99997    Rahul Patel    9.195276e+11       SOUTH
99998    POOJA Gupta    9.171351e+11       north
99999    Kavya Reddy    9.190548e+11   Northeast

[100000 rows x 3 columns]

### 3.Boolean Filtering

In [45]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 25 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Order_ID          99500 non-null   object
 1   Order_Date        98990 non-null   object
 2   Delivery_Date     97031 non-null   object
 3   Customer_Name     99014 non-null   object
 4   Customer_Email    99018 non-null   object
 5   Customer_Phone    98996 non-null   float64
 6   Customer_City     93215 non-null   object
 7   Customer_State    88108 non-null   object
 8   Customer_Pincode  99035 non-null   float64
 9   Region            81744 non-null   object
 10  Category          93659 non-null   object
 11  Sub_Category      98995 non-null   object
 12  Product_Name      97992 non-null   object
 13  Product_SKU       100000 non-null  object
 14  Quantity          100000 non-null  int64
 15  Unit_Price_INR    99500 non-null   object
 16  Discount_Percent  98926 non-null   float64
 17  Tax_Percent       98027 non-null   float64
 18  Gross_Amount_INR  100000 non-null  float64
 19  Net_Amount_INR    97045 non-null   float64
 20  Payment_Method    86780 non-null   object
 21  Payment_Status    82047 non-null   object
 22  Shipping_Method   77579 non-null   object
 23  Customer_Rating   98006 non-null   float64
 24  Return_Status     90628 non-null   object
dtypes: float64(7), int64(1), object(17)
memory usage: 19.1+ MB

In [46]:
df['Quantity'] > 5

0        False
1         True
2        False
3         True
4        False
         ...
99995    False
99996     True
99997     True
99998    False
99999     True
Name: Quantity, Length: 100000, dtype: bool

In [56]:
df[df['Quantity'] > 5]

,Order_ID,Order_Date,Delivery_Date,Customer_Name,Customer_Email,Customer_Phone,Customer_City,Customer_State,Customer_Pincode,Region,...,Unit_Price_INR,Discount_Percent,Tax_Percent,Gross_Amount_INR,Net_Amount_INR,Payment_Method,Payment_Status,Shipping_Method,Customer_Rating,Return_Status
1,ORD00000002,2023-12-11,2023-12-12,suresh Kumar,suresh.kumar998yahoo.co.in,9.193598e+11,PUNE,Maharashtra,186238.0,East India,...,140712.99,4.39,12.0,984990.93,1054759.81,NaN,Pending,Next Day,4.5,1
3,ORD00000004,2024-03-31,2024-04-06,Pooja Das,pooja.das184gmail.com,9.171830e+11,Kolkata,Andhra Pradesh,739883.0,SOUTH,...,132045.51,17.80,0.0,1591319.56,1308064.68,Debit Card,Paid,Same Day,4.0,Yes
7,ORD00000008,2022-09-04,2022-09-07,Rajesh Bose,rajesh.bose319@outlook.com,9.183183e+11,Kanpur,Maharashtra,6847.0,Central,...,79629.06,19.59,0.0,557403.42,448208.09,EMI,pending,NaN,1.0,1
9,ORD00000010,2024-03-29,2024-04-06,Kavya Gupta,kavya.gupta430@yahoo.co.in,9.186384e+11,Ahmedabad,Gujarat,194758.0,Northeast,...,143389.29,36.43,18.0,1290503.61,968040.31,Debit Card,Failed,EXPRESS,2.2,No
11,ORD00000012,2020-02-17,2020-02-29,Vikram Verma,vikram.verma927@rediffmail.com,9.189287e+11,kolkata,MH,715299.0,NaN,...,128489.73,24.99,28.0,899428.11,863566.11,Netbanking,pending,Same Day,3.0,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99992,ORD00099993,2022-06-29,2022-07-04,Arun Singh,arun.singh266gmail.com,9.172597e+11,Bangalroe,Telangana,172945.0,East,...,74524.1,57.67,0.0,447144.60,189276.31,credit card,PAID,EXPRESS,2.9,NaN
99994,ORD00099995,2021-05-06,2021-05-12,Vikram Sen,vikram.sen531@yahoo.co.in,9.173590e+11,Pune,Bihar,763139.0,SOUTH,...,53422.72,50.12,5.0,320536.32,167877.69,COD,Pending,Economy,2.8,TRUE
99996,ORD00036659,2022-05-21,2022-05-27,meena Rao,meena.rao409@hotmail.com,9.168083e+11,PUNE,NaN,614404.0,North,...,57356.55,31.30,5.0,401495.85,289619.03,Cash on Delivery,PAID,Standard,1.4,Yes
99997,ORD00099998,03-Oct-2023,14-Oct-2023,Rahul Patel,rahul.patel827@rediffmail.com,9.195276e+11,NaN,Bihar,250996.0,SOUTH,...,119512.97,22.06,12.0,1075616.73,938935.96,Credit Card,PAID,NaN,1.9,No Return
99999,ORD00100000,01-25-2024,02-06-2024,Kavya Reddy,kavya.reddy225@outlook.com,9.190548e+11,PUNE,Maharashtra,343131.0,Northeast,...,119670.92,57.04,0.0,718025.52,308463.76,DEBIT CARD,PAID,Express,4.2,1

In [52]:
df['Order_Date'] > '2024/01/01'

0         True
1        False
2        False
3        False
4        False
         ...
99995    False
99996    False
99997    False
99998    False
99999    False
Name: Order_Date, Length: 100000, dtype: bool

In [54]:
df['Customer_City'] == 'Chenai'

0         True
1        False
2        False
3        False
4        False
         ...
99995    False
99996    False
99997    False
99998    False
99999    False
Name: Customer_City, Length: 100000, dtype: bool

In [55]:
df[df['Customer_City'] == 'Chenai']

,Order_ID,Order_Date,Delivery_Date,Customer_Name,Customer_Email,Customer_Phone,Customer_City,Customer_State,Customer_Pincode,Region,...,Unit_Price_INR,Discount_Percent,Tax_Percent,Gross_Amount_INR,Net_Amount_INR,Payment_Method,Payment_Status,Shipping_Method,Customer_Rating,Return_Status
0,ORD00000001,28/09/2023,07/10/2023,Rohan Agarwal,rohan.agarwal769@yahoo.co.in,9.186701e+11,Chenai,KA,684090.0,NaN,...,119742.81,26.31,5.0,119742.81,92650.40,cash,NaN,Next Day,4.4,N
30,ORD00000031,10/01/2024,13/01/2024,arun Rao,arun.rao671@hotmail.com,9.186673e+11,Chenai,NaN,252458.0,NaN,...,101877.29,36.68,0.0,305631.87,193526.10,COD,Paid,NaN,7.3,Returned
36,ORD00000037,02-Oct-2020,07-Oct-2020,ARJUN Gupta,arjun.gupta460@yahoo.co.in,9.162136e+11,Chenai,Haryana,688128.0,West,...,94545.41,29.74,18.0,756363.28,627076.59,credit card,paid,Economy,4.6,Yes
41,ORD00000042,04-24-2022,05-01-2022,Kiran Agarwal,kiran.agarwal284@outlook.com,9.199605e+11,Chenai,NaN,947467.0,NaN,...,52127.12,50.59,12.0,364889.84,201927.12,DEBIT CARD,NaN,NaN,1.8,Y
140,ORD00000141,2021-05-05,2021-05-15,Anjali Verma,anjali.verma735@rediffmail.com,9.199603e+11,Chenai,NaN,920381.0,East India,...,INR 19007.23,42.94,18.0,76028.92,51190.88,DEBIT CARD,FAILED,Economy,4.3,TRUE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99888,ORD00099889,01-22-2021,01-23-2021,Meena Verma,meena.verma341@outlook.com,9.196612e+11,Chenai,KA,850676.0,East,...,53856.31,47.89,5.0,430850.48,NaN,UPI,FAILED,Next Day,-4.6,FALSE
99913,ORD00099914,2021-09-06,2021-09-09,Rajesh Iyer,rajesh.iyer955@yahoo.co.in,9.190091e+11,Chenai,Rajasthan,853845.0,Central,...,5615.73,21.18,28.0,16847.19,16997.06,Net Banking,FAILED,NaN,4.6,TRUE
99949,ORD00099950,2020-05-29,2020-06-09,Pooja Kumar,pooja.kumar701@hotmail.com,9.191316e+11,Chenai,Karnataka,296874.0,NaN,...,134795.14,50.41,5.0,539180.56,280748.62,credit card,Failed,NaN,4.9,N
99960,ORD00099961,14/03/2021,20/03/2021,Rohan Mishra,rohan.mishra224@hotmail.com,9.179096e+11,Chenai,NaN,361116.0,NaN,...,112639.88,4.62,5.0,901119.04,902461.71,Netbanking,pending,Next Day,4.4,Y
99990,ORD00099991,2023/12/19,2023/12/25,ARUN Chopra,arun.chopra949@gmail.com,9.198547e+11,Chenai,Maharashtra,857407.0,Northeast,...,121314.05,54.27,0.0,513446.01,234798.86,Wallet,NaN,Economy,2.7,0